### ISSUE TITLE
Wrong Logo on StairCase

### ISSUE THREAD

**Issue by iainmcd** [codemicro/ukvbeta#8] opened 2018-07-23 22:51 UTC
**Describe the bug**
Jet Aviation logo appears on the Staircase

**Models involved**
Staircase. (I think this is the large)

**Screenshots**
![image](https://user-images.githubusercontent.com/41571464/43107002-f2f18a9a-8ed2-11e8-9433-822a943635b8.png)

**Desktop (please complete the following information):**
Simulator version: P3D v4.3
Beta version: 1.3.3
Addons in use:
Scenery : UK2000 Heathrow Extreme
Plane : FeelThere Embraer E170
GSX Config for location :
![image](https://user-images.githubusercontent.com/41571464/43107067-43cecec8-8ed3-11e8-888b-012c6c3cd78e.png)

**Additional context**
Screenshot taken during Boarding

**Comment by codemicro** [comment] 2018-07-24 07:58
Duplicate of #7 
See that one for solution (when I figure it out 😁 )

**Closed by codemicro** 2018-07-24 07:58 UTC

**Comment by iainmcd** [comment] 2018-07-25 19:48
I can confirm that this issue was fixed in v1.3.3.2 for the Staircase (Still a problem for the cargo loader being tracked as #7 

![image](https://user-images.githubusercontent.com/41571464/43223771-060ad5a8-904c-11e8-9abd-54712c2fd4af.png)
